### ISSUE TITLE
Cython.Compiler.Errors

### ISSUE THREAD

**Issue by Josh00-Lu** [agrimgupta92/derl#1]
After running ./scripts/run_docker_cpu.sh python tools/evolution.py --cfg ./configs/evo/ft_test.yml NODE_ID 0

```shell
/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/cymj.pyx:127:21: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (const char *) except * nogil'.
Traceback (most recent call last):
  File "tools/evolution.py", line 18, in <module>
    from derl.envs.morphology import SymmetricUnimal
  File "/user/derl/derl/envs/morphology.py", line 12, in <module>
    from derl.utils import mjpy as mu
  File "/user/derl/derl/utils/mjpy.py", line 4, in <module>
    from mujoco_py import MjSim
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/builder.py", line 506, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/builder.py", line 234, in _build_impl
    dist.ext_modules = cythonize([self.extension])
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/user/miniconda/envs/docker_env/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /user/miniconda/envs/docker_env/lib/python3.6/site-packages/mujoco_py/cymj.pyx
```

**Comment by 66Lau** [comment]
I got same error while running `./scripts/run_docker_cpu.sh python tools/evolution.py --cfg ./configs/evo/ft_test.yml NODE_ID 0
`

**Comment by sunrainyg** [comment]
`pip install "cython<3"` works for me

**Comment by Yueee0-0** [comment]
@sunrainyg Have you solved it already? It didn't work on me.

**Comment by Yueee0-0** [comment]
@Josh00-Lu Have you solved it already? I met the same question.

**Comment by Yueee0-0** [comment]
`pip install cython==3.0.0a10`works for me
At the same time, I made a new docker for visualization
